### Register
POST http://localhost:5000/auth/register
Content-Type: application/json

{
  "username": "Daniel Ghannadi",
  "email": "danielghannadi1206@gmail.com",
  "password": "Daniel1402@Ghannadi1384",
  "role": "admin"
}


### Login
POST http://localhost:5000/auth/login
Content-Type: application/json

{
  "email": "danielghannadi1206@gmail.com",
  "password": "Daniel1402@Ghannadi1384"
}
###
GET http://localhost:5000/users/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJkYW5pZWxnaGFubmFkaTEyMDZAZ21haWwuY29tIiwicm9sZSI6InVzZXIiLCJpYXQiOjE3NjI3MDM5ODQsImV4cCI6MTc2MjcwNzU4NH0.a7MKY0DKl-jQdoXpnVa5b2fOBO97UjZcqoRNcW_MKeE


